#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/include/lib.php"
RC="$ROOT/src/rootfs/etc/rc.d/rc.unmotion"
SEED="$ROOT/src/rootfs/usr/local/sbin/unmotion-seed-worker"
WORKER="$ROOT/src/rootfs/usr/local/sbin/unmotion-worker"
BUILD="$ROOT/scripts/build.sh"
CLONE_WORKER="$ROOT/src/rootfs/usr/local/sbin/unmotion-clone-worker"
CLONE_TRANSFORM="$ROOT/src/rootfs/usr/local/sbin/unmotion-clone-transform"
GUEST_CUSTOMIZE="$ROOT/src/rootfs/usr/local/sbin/unmotion-guest-customize"

grep -Eq 'const[[:space:]]+UNM_PROTOCOL[[:space:]]*=[[:space:]]*5;' "$LIB"
grep -q "const UNM_VERSION = '0.3.1-RC2';" "$LIB"
grep -q '<txt-record>protocol=5</txt-record>' "$RC"
grep -q 'receive_resume_token' "$SEED"
grep -q 'zfs send -t' "$SEED"
grep -q 'DEST_DEDUP_REMOTE' "$SEED"
grep -Fq "IFS=\$'\\034' read -r kind src dst snap" "$SEED"
grep -q 'destination receive state is temporarily unavailable' "$SEED"
grep -q 'Transfer plan:' "$WORKER"
grep -q 'bytes=' "$WORKER"
grep -q 'if ((WARM_MODE));then args+=(--inplace --no-whole-file);else args+=(--partial-dir=.unmotion-partial);fi' "$WORKER"
grep -q 'protect_warm_images' "$WORKER"
grep -q 'function unmParseAvahiTxtRecordList' "$LIB"
grep -Fq 'SAFE_VERSION="${SAFE_VERSION,,}"' "$BUILD"
grep -Fq 'AUTHOR="Richard Skinner"' "$BUILD"
grep -Fq '<!ENTITY author "$AUTHOR">' "$BUILD"
grep -Fq 'find "$STAGE" -type d -exec chmod 0755 {} +' "$BUILD"
grep -Fq 'Unsafe package directory mode:' "$BUILD"
grep -q 'function unmClonePreflight' "$LIB"
grep -q 'function unmCloneDatasetIsolated' "$LIB"
grep -Fq 'zfs send -cp "$srcsnap" | "${receive[@]}" "$destination"' "$CLONE_WORKER"
grep -Fq 'exact cleanup is incomplete and was not reported as successful' "$CLONE_WORKER"
grep -Fq 'exact clone destinations were verified absent' "$CLONE_WORKER"
grep -Fq 'persistent XML remains after cleanup retries' "$CLONE_WORKER"
grep -Fq 'exact clone directory' "$CLONE_WORKER"
grep -Fq 'virsh dominfo "$CLONE_UUID"' "$CLONE_WORKER"
! grep -Fq 'virsh domuuid "$CLONE_UUID"' "$CLONE_WORKER"
grep -Fq 'unset "CREATED_SNAPS[$last_snap_index]"' "$CLONE_WORKER"
! grep -Fq 'CREATED_SNAPS=("${CREATED_SNAPS[@]/$srcsnap}")' "$CLONE_WORKER"
! grep -Fq 'zfs snapshot -r' "$CLONE_WORKER"
! grep -Fq 'zfs send -R' "$CLONE_WORKER"
grep -Fq 'GUEST_CUSTOMIZATION' "$CLONE_WORKER"
grep -Fq "Refusing to clone virtual TPM XML" "$CLONE_TRANSFORM"
grep -Fq "strtolower((string)(\$os['id']??''))!=='ubuntu'" "$GUEST_CUSTOMIZE"
echo 'Static RC2 regression markers are present.'
