#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/include/lib.php"
RC="$ROOT/src/rootfs/etc/rc.d/rc.unmotion"
SEED="$ROOT/src/rootfs/usr/local/sbin/unmotion-seed-worker"
WORKER="$ROOT/src/rootfs/usr/local/sbin/unmotion-worker"
BUILD="$ROOT/scripts/build.sh"

grep -Eq 'const[[:space:]]+UNM_PROTOCOL[[:space:]]*=[[:space:]]*5;' "$LIB"
grep -q "const UNM_VERSION = '0.3.0-RC1';" "$LIB"
grep -q '<txt-record>protocol=5</txt-record>' "$RC"
grep -q 'receive_resume_token' "$SEED"
grep -q 'zfs send -t' "$SEED"
grep -q 'DEST_DEDUP_REMOTE' "$SEED"
grep -Fq "IFS=\$'\\034' read -r kind src dst snap" "$SEED"
grep -q 'destination receive state is temporarily unavailable' "$SEED"
grep -q 'Transfer plan:' "$WORKER"
grep -q 'bytes=' "$WORKER"
grep -q 'if ((WARM_MODE));then args+=(--inplace --no-whole-file);else args+=(--partial-dir=.unmotion-partial);fi' "$WORKER"
grep -q 'protect_warm_images' "$WORKER"
grep -q 'function unmParseAvahiTxtRecordList' "$LIB"
grep -Fq 'SAFE_VERSION="${SAFE_VERSION,,}"' "$BUILD"
grep -Fq 'AUTHOR="Richard Skinner"' "$BUILD"
grep -Fq '<!ENTITY author "$AUTHOR">' "$BUILD"
echo 'Static RC1 regression markers are present.'
