#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/include/lib.php"
RC="$ROOT/src/rootfs/etc/rc.d/rc.unmotion"
SEED="$ROOT/src/rootfs/usr/local/sbin/unmotion-seed-worker"
WORKER="$ROOT/src/rootfs/usr/local/sbin/unmotion-worker"
BUILD="$ROOT/scripts/build.sh"
CLONE_WORKER="$ROOT/src/rootfs/usr/local/sbin/unmotion-clone-worker"
CLONE_TRANSFORM="$ROOT/src/rootfs/usr/local/sbin/unmotion-clone-transform"
GUEST_CUSTOMIZE="$ROOT/src/rootfs/usr/local/sbin/unmotion-guest-customize"
PAGE="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/UnMotion.page"
UI="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/js/unmotion.js"
UI_CSS="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/css/unmotion.css"
API="$ROOT/src/rootfs/usr/local/emhttp/plugins/unmotion/api.php"
REPLICATION_WORKER="$ROOT/src/rootfs/usr/local/sbin/unmotion-replication-worker"
REPLICATION_SCHEDULER="$ROOT/src/rootfs/usr/local/sbin/unmotion-replication-scheduler"

grep -Eq 'const[[:space:]]+UNM_PROTOCOL[[:space:]]*=[[:space:]]*5;' "$LIB"
grep -q "const UNM_VERSION = '0.4.0-beta1';" "$LIB"
grep -q '<txt-record>protocol=5</txt-record>' "$RC"
grep -q 'receive_resume_token' "$SEED"
grep -q 'zfs send -t' "$SEED"
grep -q 'DEST_DEDUP_REMOTE' "$SEED"
grep -Fq "IFS=\$'\\034' read -r kind src dst snap" "$SEED"
grep -q 'destination receive state is temporarily unavailable' "$SEED"
grep -q 'Transfer plan:' "$WORKER"
grep -q 'bytes=' "$WORKER"
grep -q 'if ((WARM_MODE));then args+=(--inplace --no-whole-file);else args+=(--partial-dir=.unmotion-partial);fi' "$WORKER"
grep -q 'protect_warm_images' "$WORKER"
grep -q 'function unmParseAvahiTxtRecordList' "$LIB"
grep -Fq 'SAFE_VERSION="${SAFE_VERSION,,}"' "$BUILD"
grep -Fq 'AUTHOR="Richard Skinner"' "$BUILD"
grep -Fq '<!ENTITY author "$AUTHOR">' "$BUILD"
grep -Fq 'find "$STAGE" -type d -exec chmod 0755 {} +' "$BUILD"
grep -Fq 'Unsafe package directory mode:' "$BUILD"
grep -q 'function unmClonePreflight' "$LIB"
grep -q 'function unmCloneDatasetIsolated' "$LIB"
grep -Fq 'zfs send -cp "$srcsnap" | "${receive[@]}" "$destination"' "$CLONE_WORKER"
grep -Fq 'exact cleanup is incomplete and was not reported as successful' "$CLONE_WORKER"
grep -Fq 'exact clone destinations were verified absent' "$CLONE_WORKER"
grep -Fq 'persistent XML remains after cleanup retries' "$CLONE_WORKER"
grep -Fq 'exact clone directory' "$CLONE_WORKER"
grep -Fq 'virsh dominfo "$CLONE_UUID"' "$CLONE_WORKER"
! grep -Fq 'virsh domuuid "$CLONE_UUID"' "$CLONE_WORKER"
grep -Fq 'unset "CREATED_SNAPS[$last_snap_index]"' "$CLONE_WORKER"
! grep -Fq 'CREATED_SNAPS=("${CREATED_SNAPS[@]/$srcsnap}")' "$CLONE_WORKER"
! grep -Fq 'zfs snapshot -r' "$CLONE_WORKER"
! grep -Fq 'zfs send -R' "$CLONE_WORKER"
grep -Fq 'GUEST_CUSTOMIZATION' "$CLONE_WORKER"
grep -Fq "Refusing to clone virtual TPM XML" "$CLONE_TRANSFORM"
grep -Fq "strtolower((string)(\$os['id']??''))!=='ubuntu'" "$GUEST_CUSTOMIZE"
grep -Eq 'const[[:space:]]+UNM_REPLICATION_PROTOCOL[[:space:]]*=[[:space:]]*1;' "$LIB"
grep -Fq "'replicationProtocolVersion'=>UNM_REPLICATION_PROTOCOL" "$LIB"
grep -Fq "'scheduledReplication'=>true" "$LIB"
grep -Fq '@unlink(unmReplicationRuntimePath($id));' "$LIB"
grep -Fq 'Scheduled Replications' "$PAGE"
grep -Fq 'inert recovery inventory' "$PAGE"
grep -Fq 'Incoming Replica Inventory' "$PAGE"
grep -Fq 'replicationRpoNotches' "$UI"
grep -Fq "{seconds:300,label:'5 min'}" "$UI"
grep -Fq "{seconds:900,label:'15 min'}" "$UI"
grep -Fq "{seconds:1800,label:'30 min'}" "$UI"
grep -Fq "{seconds:3600,label:'1 hour'}" "$UI"
grep -Fq "{seconds:7200,label:'2 hours'}" "$UI"
grep -Fq "{seconds:14400,label:'4 hours'}" "$UI"
grep -Fq "{seconds:21600,label:'6 hours'}" "$UI"
grep -Fq "{seconds:28800,label:'8 hours'}" "$UI"
grep -Fq "{seconds:43200,label:'12 hours'}" "$UI"
grep -Fq "{seconds:86400,label:'24 hours'}" "$UI"
grep -Fq 'Math.min(24,Math.floor(86400/Number(seconds||3600)))' "$UI"
grep -Fq "post(activeReplicationId?'updateReplication':'createReplication'" "$UI"
grep -Fq "post('runReplicationNow'" "$UI"
grep -Fq "post('setReplicationEnabled'" "$UI"
grep -Fq "post('removeReplication'" "$UI"
grep -Fq "?'replicationLog':'jobLog'" "$UI"
grep -Fq 'ZFS Master' "$UI"
grep -Fq 'QEMU Guest Agent is not currently responding' "$UI"
grep -Fq 'Power cycle (recommended)' "$UI"
grep -Fq 'Best-effort stun' "$UI"
grep -Fq 'Not activatable in beta1' "$UI"
grep -Fq 'Replica removal deferred' "$UI"
grep -Fq 'Number(policy.generation||0)===0&&!policy.baseSnapshot&&!policy.pending' "$UI"
grep -Fq "['STARTING','LOCKING','PREFLIGHT','PROBING_GUEST','QUIESCING','SNAPSHOTTING','THAWING','CAPTURING_HOST_STATE','TRANSFERRING','VERIFYING','PUBLISHING','COMMITTING','PRUNING','CLEANING']" "$UI"
grep -Fq 'Disabling a policy pauses future runs while preserving replica data and resumable state' "$PAGE"
! grep -Fq "post('activateReplica'" "$UI"
grep -Fq '.unm-slider-notches' "$UI_CSS"
for replication_action in replications incomingReplicas replicationPreflight createReplication updateReplication setReplicationEnabled runReplicationNow removeReplication replicationLog; do
  grep -Fq "case '$replication_action':" "$API"
done
[[ "$(grep -c 'requirePostMutation();' "$API")" -ge 5 ]]
grep -Fq 'receive_resume_token' "$REPLICATION_WORKER"
grep -Fq 'zfs send -t "$token"' "$REPLICATION_WORKER"
grep -Fq 'zfs send -cp -i "$src@$base" "$src@$SNAPSHOT_NAME"' "$REPLICATION_WORKER"
grep -Fq '[[ "$src_guid" == "$dst_guid" ]]' "$REPLICATION_WORKER"
grep -Fq 'function unmAssertReplicaVmUuidUndefined' "$LIB"
[[ "$(sed -n '/^function unmReplicaPublish/,/^}/p' "$LIB" | grep -Fc 'unmAssertReplicaVmUuidUndefined($identity['"'"'vmUuid'"'"']);')" == 2 ]]
grep -Fq 'Destination already defines a VM with the replica UUID.' "$LIB"
grep -Fq 'A safe replica checkpoint requires a transferred archive covering every declared TPM and NVRAM device.' "$LIB"
grep -Fq 'function unmGarbageCollectReplicaCheckpointArchives' "$LIB"
grep -Fq 'Unreferenced checkpoint archive failed its ownership hash check and was preserved' "$LIB"
grep -Fq 'zfs snapshot -o "com.unmotion:replication=$POLICY_ID"' "$REPLICATION_WORKER"
! grep -Fq 'zfs snapshot -r' "$REPLICATION_WORKER"
! grep -Fq 'zfs send -R' "$REPLICATION_WORKER"
! grep -Fq 'zfs destroy -r' "$REPLICATION_WORKER"
grep -Fq 'flock -n 9 || exit 0' "$REPLICATION_SCHEDULER"
grep -Fq 'slot=$((now-now%interval))' "$REPLICATION_SCHEDULER"
echo 'Static migration and scheduled-replication regression markers are present.'
